#!/bin/bash

laptop="laptop"
desktop="desktop"

if [ ! -d "$HOME/.config/polybar" ]; then 
    mkdir $HOME/.config/polybar
fi

if [ ! -d "$HOME/.config/spicetify/Themes/Yoo" ]; then
    mkdir $HOME/.config/spicetify/Themes/Yoo
fi

if [ ! -d "$HOME/.config/rofi" ]; then
    mkdir $HOME/.config/rofi
fi

echo "Configuring apps..."
sleep 0.1

cd /home/margarida/Documents/dotfiles/Apps

cp -r ranger $HOME/.config/

cp -r polybar/* $HOME/.config/polybar/

cd /home/margarida/Documents/dotfiles/Configs

cp redshift.conf $HOME/.config/

cp compton.conf $HOME/.config/compton.conf
cp picom.conf $HOME/.config/picom.conf

# Dunst and Xresources needs to be updated, and then sent to it's place
cp dunstrc $HOME/.config/wal/templates
cp -a .Xresources $HOME/.config/wal/templates

python /home/margarida/Documents/dotfiles/Scripts/pythonScripts/wallpaperAndColorScheme.py

cp $HOME/.cache/wal/dunstrc $HOME/.config/dunst/
cp $HOME/.cache/wal/.Xresources $HOME/

cp /home/margarida/Documents/dotfiles/Configs/config.ini $HOME/.config/spicetify

cp -r /home/margarida/Documents/dotfiles/Apps/spicetify/* $HOME/.config/spicetify/Themes/Yoo

spicetify update

echo "Configuring setup..."
sleep 0.1

cd /home/margarida/Documents/dotfiles 

if [ $1 == $laptop ]
then 
    cd /home/margarida/Documents/dotfiles/Laptop
    
    touch $HOME/.config/i3/config
    rm $HOME/.config/i3/config

    cat ../Configs/i3-common-config ../Configs/i3-windows ../Configs/i3-keybindings ../Configs/i3-autostart i3-laptop-config >> $HOME/.config/i3/config
    
    cp polybar/config $HOME/.config/polybar

elif [ $1 == $desktop ]
then
    cd /home/margarida/Documents/dotfiles/Desktop

    touch $HOME/.config/i3/config
    rm $HOME/.config/i3/config
    
    cat ../Configs/i3-common-config ../Configs/i3-windows ../Configs/i3-keybindings ../Configs/i3-autostart i3-desktop-config >> $HOME/.config/i3/config
    
    cp polybar/config $HOME/.config/polybar

fi


echo "Updated $1, homie."
sleep 0.1

exit 0
E