#!/bin/bash

laptop="laptop"
desktop="desktop"

DOTFILES_DIR=${PWD}

read -p "On which device are you installing my dude? 'laptop' or 'desktop'?  " device

echo "Got you fam, installing on $device."
./Scripts/bashScripts/addToPath

# This is also done right now so that the rest of the script can go along nicely, even without a reboot
export DOTFILES_DIR=/home/margarida/Documents/dotfiles
export PATH=$PATH:/home/margarida/Documents/dotfiles

cd Scripts

./setupScripts/touchInitialFiles

./setupScripts/installRicePrograms $device

# Remove fish intro message
# echo 'set -U fish_greeting ""' >> .config/fish/config.fish

echo "There is a list of programs at Scripts/setupScripts/extraProgramsToInstall . You can modify this file now if you want, to download exactly what you need!"
sleep 2

read -p "Do you want to install the extra programs at Scripts/setupScripts/extraProgramsToInstall.sh? (y/n)  " answer
if [ $answer == "y" ]
then 
	./setupScripts/extraProgramsToInstall.sh $device "arch-based"
fi

./setupScripts/setupLightDM /home/margarida/Documents/dotfiles

./setupScripts/setupSpicetify /home/margarida/Documents/dotfiles

cd ..

# Fix small ranger error 
echo "set preview_script $HOME/.config/ranger/scope.sh" >> Apps/ranger/rc.conf

echo "\nSetting up $device configurations..."
sleep 1

./update.sh $device

cd /home/margarida/Documents/dotfiles/Scripts

./setupScripts/installFonts
killall i3bar
	
if [ $device == $laptop ]
then
	polybar main

	echo "Configuring TLP for better battery management..."
	sleep 1

	./setupTLP

	read -p "Do you want to setup Prime? (y/n)  " answer

	if [ $answer == "y" ]
	then 
		sudo pacman -S nvidia lib32-nvidia-utils xf86-video-intel nvidia-prime
		sudo mv /home/margarida/Documents/dotfiles/Configs/30-nvidia.conf /etc/X11/xorg.conf.d/
	fi 

elif [ $device == $desktop ]
then
	polybar left && polybar right
fi

# Installing GRUB theme 
echo "Installing GRUB theme..."
sleep 1

sudo /home/margarida/Documents/dotfiles/Apps/grub/install.sh -v

# First wal run
python /home/margarida/Documents/dotfiles/Scripts/pythonScripts/wallpaperAndColorScheme.py

# Fix small error for VLC downloading
mkdir ~/.cache/vlc

echo "Setting up WPGTK theme... (CHANGE LATER WITH LXAPPEARANCE TO FLATCOLOR THEME AND ICON PACK)"
sleep 3

wpg-install.sh -i
wpg-install.sh -g

echo "Change line 93 of this script if you want another lockscreen wallpaper."
sleep 2 

betterlockscreen -u /home/margarida/Documents/dotfiles/Wallpapers/wallhaven-83do1o.jpg 

echo "If you want to configure VPN, you can do it now."
sleep 3

echo "And that's it! Exiting."
sleep 2


