#!/bin/bash

laptop="laptop"
desktop="desktop"

arch-based="arch-based"
void="void"

echo "Installing extra programs..."
sleep 1

if [ $2 == $void ]
then
    sudo xbps-install -S epdfview neofetch unzip sl redshift gnome-system-monitor pavucontrol vlc authy nautilus firefox telegram-desktop franz-bind visual-studio-code-bin transmission-qt discord youtube-dl steam

    # Missing packages 
    # Simplenote electron-bin
    # Franz
    # Authy 
    
    if [ $1 == $laptop ]
    then
        sudo xbps-install xorg-xbacklight powertop tlp
    elif [ $1 == $desktop ]
    then
        sudo xbps-install xf86-input-wacom pureref xf86-video-amdgpu
        sudo cp /home/margarida/Documents/dotfiles/Configs/20-amdgpu.conf /etc/X11/xorg.conf.d/
    fi

elif [ $1 == $arch-based ]
then
    yay -S epdfview neofetch unzip sl redshift gnome-system-monitor pavucontrol vlc nautilus firefox telegram-desktop visual-studio-code-bin transmission-qt franz-bin discord youtube-dl steam

    if [ $1 == $laptop ]
    then
        yay -S xorg-xbacklight blacklist_pcspkr
    # Spotify sometimes breaks
    yay -S spotify
fi




