#!/bin/bash

sudo cp /home/margarida/Documents/dotfiles/Scripts/setupScripts/installBlender /bin
sudo cp /home/margarida/Documents/dotfiles/Scripts/setupScripts/installGodot /bin
sudo cp /home/margarida/Documents/dotfiles/Scripts/setupScripts/installKrita /bin
sudo cp /home/margarida/Documents/dotfiles/Scripts/bashScripts/newsAndEntertainmentSync /bin
sudo cp /home/margarida/Documents/dotfiles/Scripts/bashScripts/xauuuuuuuu /bin
sudo cp /home/margarida/Documents/dotfiles/Scripts/bashScripts/workingTime /bin
sudo cp /home/margarida/Documents/dotfiles/Scripts/bashScripts/drawingMode /bin

sudo cp /home/margarida/Documents/dotfiles/Scripts/setupScripts/update* /bin