#!/bin/bash

#xrandr --output HDMI-A-1 --off
#xrandr --output DisplayPort-1 --off

killall picom

xrandr --output DP-0 --primary --mode 2560x1440 --rate 144.00 --pos 0x0 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 2560x-120 --rotate left

killall polybar
polybar right &
polybar left &
picom --experimental-backends &