#!/bin/bash

#xrandr --output DisplayPort-1 --off

killall picom 

xrandr --output HDMI-1 --off

xrandr --output DP-0 --primary --mode 2560x1440 --rate 144.00 --rotate normal

killall polybar
polybar left &
picom --experimental-backends &